### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Tikam02** [heisenberg47/crowd-counting-I#5]
FileNotFoundError: [Errno 2] No such file or directory: '_ann.mat'

**Comment by Tikam02** [comment]
images_ann = []

for image_name in images:
    images_ann.append(scipy.io.loadmat(image_name.split('.')[0] + '_ann.mat')['annPoints'])

**Comment by Tikam02** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '_ann.mat'

**Comment by haroldteng** [comment]
@Tikam02 how did you solve this?
